Фикс данных, проверка работы репозитория
htmlacademy-vue/275301-pizza-1 pull request #1
Opened 2021-07-04 08:24 UTC by SokolovAG

2021-07-04 11:48 UTC, gustoase requested changes
Все получилось хорошо, но есть пару нюансов)

2021-07-04 11:48 UTC, gustoase commented on src/frontend/src/common/contstants.js
> +export const DOUGH_TYPE = [
Я бы посоветовал использовать сделать все через Set() https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Set/Set

Плюсы подхода с Set в том, что не надо будет в normalizeDoughType реализовывать поиск через findIndex, достаточно получить по ключу нужное значение и все.

2021-07-04 11:48 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +      dough: pizza.dough.map((dough_type) => normalizeDoughType(dough_type)),
Так в принципе можно делать, но data не кешируется в отличии от cumputed, мелочь, а приятно)

2021-07-04 11:56 UTC, SokolovAG commented on src/frontend/src/views/Index.vue
> +      dough: pizza.dough.map((dough_type) => normalizeDoughType(dough_type)),
Окей, понял, займусь на тогда на днях c Set и функции перепишу в computed! :)
Как раз не практиковался ни с Set(), ни с Map(), будет дополнительный прокач, если зависну, запишусь на консультацию)

2021-07-04 11:57 UTC, gustoase commented on src/frontend/src/views/Index.vue
> +      dough: pizza.dough.map((dough_type) => normalizeDoughType(dough_type)),
Хорошо, проблем не должно быть, там все просто)

2021-07-04 12:45 UTC, gustoase commented on src/frontend/src/common/contstants.js
> +export const DOUGH_TYPE = [
Ошибся, тут не Set а Map юзать надо

2021-07-15 12:48 UTC, gustoase approved these changes

2021-07-15 12:49 UTC, merged